postApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.homePage, name='homePage'),
    path('post/all/',views.allPost,name ='allPost'),
    path('post/add/',views.addPost,name ='addPost'),
    path('post/view/<int:pk>/',views.postDetail,name ='postDetail'),
    path('post/delete/<int:pk>/',views.deletePost,name ='deletePost'),
    path('post/edit/<int:pk>/',views.editPost,name ='editPost'),
]

postProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('postApp.urls')),
]

postApp/models.py
from django.db import models
from datetime import datetime

class Post(models.Model):
    title = models.CharField("Title",max_length=255)
    postDate = models.DateTimeField("Published date",default=datetime.now)
    image = models.CharField("Image",max_length=500, blank=True,null=True)
    content = models.TextField("Content")


    def __str__(self):
        return f"{self.title} - {self.postDate}"

postApp/forms.py
from django import forms
from .models import Post
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class NewUserForm(UserCreationForm):
    class Meta:
        fields = ('username','first_name','last_name','email','password1','password2')


class AddPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','image','content')

postApp/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Post
from .forms import AddPostForm

def homePage(request):
    posts = Post.objects.all().order_by('-postDate')[:3]
    return render(request,"site/home.html",{
        'posts':posts
    })


def allPost(request):
    posts = Post.objects.all().order_by('-postDate')
    return render(request, "site/all-news.html",{
        'posts':postscd
    })

def postDetail(request,pk):
    post = get_object_or_404(Post,pk=pk)
    return render(request,"user/post-detail.html",{
        'post':post
    })


def addPost(request):
    if request.method =="POST":
        form = AddPostForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("homePage")
    else:
        form = AddPostForm()

    return render(request,"user/add-post.html",{
        'form':form
    })

def deletePost(request,pk):
    post = get_object_or_404(Post,pk=pk)
    if request.method == "POST":
        post.delete()
        return redirect("allPost")
    return render(request,"user/delete-post.html",{
        'post':post
    })

def editPost(request,pk):
    post = get_object_or_404(Post,pk=pk)
    form = AddPostForm(request.POST or None, instance=post)
    if request.method =="POST":
        if form.is_valid():
            form.save()
            return redirect("postDetail",pk=post.pk)
    else:
        form = AddPostForm()
    return render(request,"user/edit-post.html",{
        'post':post,
        'form':form
    })

postApp/templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%}{%endblock%}</title>
    <link rel="stylesheet" href="{%static './css/bulma.min.css'%}">
</head>
<body>
  <nav class="navbar is-light" role="navigation" aria-label="main navigation">
    <div class="container">
      <div class="navbar-brand">
        <a class="navbar-item" href="{%url 'homePage'%}">
          <h1 class="title has-text-danger">Logo</h1>
        </a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarBasicExample" class="navbar-menu has-background-light">
        <div class="navbar-start">
        </div>

        <div class="navbar-end">
          <div class="navbar-item">
            <div class="buttons">
              <a href="{%url 'allPost'%}" class="button is-link is-outlined is-rounded">
                All posts
              </a>
              <a href="{%url 'addPost'%}" class="button is-danger is-outlined is-rounded">
                Add post
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>

  </nav>

  {%block content%}
  {%endblock%}

    <script src="{%static './js/script.js'%}"></script>
</body>
</html>

postApp/templates/site/all-news.html
{%extends '../base.html'%}

{%block title%}All news{%endblock%}


{%block content%}
  <div class="container">
    <h1 class="title mt-5 mb-5">All news</h1>
      {%for post in posts%}
    <article class="message is-danger">
        <div class="message-body">
          <h3 class="title mb-3 ">{{post.title}}</h3>
          <h4 class="subtitle mb-5">{{post.postDate}}</h4>
          <p class="mb-3">{{post.content|truncatewords:20}}</p>
          <a href="{%url 'postDetail' pk=post.pk%}" class="button is-danger">Read</a>
        </div>
    </article>
      {%endfor%}
  </div>
{%endblock%}

postApp/templates/site/home.html
{%extends '../base.html'%}

{%block title%}Main page{%endblock%}


{%block content%}
  <div class="container">
    <div class="columns">
      <div class="column is-two-thirds">
        <section class="hero is-light">
          <div class="hero-body">
            <p class="title mb-5">
              Post app portal
            </p>
            <p class="subtitle mb-3">
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veniam accusantium pariatur sed! Consequuntur veniam unde facilis eius ut a doloribus modi fuga soluta consectetur tempore et, illo ratione voluptas quo.
            </p>
            <a href="{%url 'allPost'%}" class="button is-danger">All news</a>
          </div>
        </section>
      </div>
      <div class="column ">
        <h2 class="title mt-5">Last news</h2>
        {%for post in posts%}
        <div class="card mt-5">
          <div class="card-content">
            <div class="content ">
              <h3>{{post.title}}</h3>
              <a href="{%url 'postDetail' pk=post.pk%}"  class="button is-danger">Read</a>
            </div>
          </div>
        </div>
        {%endfor%}
      </div>
    </div>

  </div>
{%endblock%}

postApp/templates/user/add-post.html
{%extends '../base.html'%}

{%block title%}Add post{%endblock%}


{%block content%}
<style>
    #id_title,#id_image,#id_content{
        display:block;
        width:100%;
        padding:8px;
        border-radius:10px;
        margin-botton:10px;
        border:1px solid #000;
    }
</style>
  <div class="container">
    <form method="post">
        <h1 class="title mt-5 mb-5">Add post</h1>
        {%csrf_token%}
        {{form}}
        <button class="mt-5 button is-danger">Add</button>
    </form>
  </div>
{%endblock%}

postApp/templates/user/delete-post.html
{%extends '../base.html'%}

{%block title%}Delete post{%endblock%}


{%block content%}
  <div class="container">
    <form method="post">
        <h1 class="title mt-5 mb-5">Delete post {{post.title}}?</h1>
        {%csrf_token%}
        <a href="{%url 'postDetail' pk=post.pk%}" class="button is-info">No</a>
        <button class=" button is-danger">Yes</button>
    </form>
  </div>
{%endblock%}

postApp/templates/user/edit-post.html
{%extends '../base.html'%}

{%block title%}Edit post{%endblock%}


{%block content%}
<style>
    #id_title,#id_image,#id_content{
        display:block;
        width:100%;
        padding:8px;
        border-radius:10px;
        margin-botton:10px;
        border:1px solid #000;
    }
</style>
  <div class="container">
    <form method="post">
        <h1 class="title mt-5 mb-5">Edit post</h1>
        {%csrf_token%}
        <label for="id_title">Title:</label>
        <input value="{{post.title}}" type="text" name="title" maxlength="255" required="" id="id_title">
        {%if post.image%}
        <label for="id_image">Image:</label>
        <input type="text" value="{{post.image}}" name="image" maxlength="500" id="id_image">
        {%else%}
        <label for="id_image">Image:</label>
        <input type="text" value="" name="image" maxlength="500" id="id_image">
        {%endif%}
        <label for="id_content">Content:</label>
        <textarea name="content" cols="40" rows="10" required="" id="id_content">
            {{post.content}}
        </textarea>
        <button class="mt-5 button is-danger">Edit</button>
    </form>
  </div>
{%endblock%}

postApp/templates/user/post-detail.html
{%extends '../base.html'%}

{%block title%}{{post.title}}{%endblock%}


{%block content%}
  <div class="container">
    <article class=" mt-5 message is-danger">
        <div class="message-body">
          <h3 class="title mb-5 ">{{post.title}}</h3>
          <h4 class="subtitle mb-5">{{post.postDate}}</h4>
          {%if post.image%}
          <div style="width:100%">
              <img src="{{post.image}}" alt="">
          </div>
          {%else%}
          <h2>Nothing</h2>
          {%endif%}
          <p class="mb-3">{{post.content}}</p>
          <a href="{%url 'editPost' pk=post.pk%}" class="button is-info">Edit</a>
          <a href="{%url 'deletePost' pk=post.pk%}" class="button is-danger">Delete</a>
        </div>
    </article>
  </div>
{%endblock%}